In [1]:
import numpy as np

In [2]:
L = [1,2,3]

In [3]:
A = np.array(L)

In [11]:
L2 = [[1,2],[3,4]]
A2 = np.array(L2)

In [12]:
print(L2)
print(A2)

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]


In [13]:
## Arrays de ceros y unos
zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 2))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)


Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [14]:
## Arrays de rangos
range_array = np.arange(10)
print("Range Array:", range_array)


Range Array: [0 1 2 3 4 5 6 7 8 9]


In [15]:
## Arrays espaciados linealmente
linspace_array = np.linspace(0, 1, num=5) 
print("Linspace Array:", linspace_array)


Linspace Array: [0.   0.25 0.5  0.75 1.  ]


In [16]:
## matriz identidad

identity_matrix = np.eye(4)
print("Identity Matrix:\n", identity_matrix)

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [17]:
## Arrays con tipos de datos especificos

int_array = np.array([1, 2, 3], dtype='int32')
float_array = np.array([1, 2, 3], dtype='float32')
print("Integer Array:", int_array)
print("Float Array:", float_array)

Integer Array: [1 2 3]
Float Array: [1. 2. 3.]
