In [2]:
import numpy as np

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [6]:
a[4]

5

In [7]:
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
 b[-1, -1]

9

In [10]:
c = np.arange(10)
print(c)

[0 1 2 3 4 5 6 7 8 9]


In [11]:
c[:5]

array([0, 1, 2, 3, 4])

In [12]:
c[3:8]

array([3, 4, 5, 6, 7])

In [14]:
c[::3]

array([0, 3, 6, 9])

In [15]:
d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [16]:
 d[:2, :2]

array([[1, 2],
       [5, 6]])

In [18]:
d[:, ::3]

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [22]:
e = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
indices = np.array([1, 3, 3])

e[indices]

array([2, 4, 4])

In [23]:
f = np.array([1, -1, -2, 3, -3, 3])

In [24]:
print(f)

[ 1 -1 -2  3 -3  3]


In [25]:
condition = f > 0
condition

array([ True, False, False,  True, False,  True])

In [26]:
 f[condition]

array([1, 3, 3])