In [33]:
import numpy as np

In [40]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [41]:
a+b

array([5, 7, 9])

In [43]:
b-10

array([-6, -5, -4])

In [44]:
a*b

array([ 4, 10, 18])

In [45]:
a/b

array([0.25, 0.4 , 0.5 ])

In [46]:
a/10

array([0.1, 0.2, 0.3])

In [48]:
a*10

array([10, 20, 30])