1. **Introducción al Broadcasting**

   El broadcasting es una característica poderosa en NumPy que permite realizar operaciones aritméticas en arrays de diferentes tamaños. Esto se logra ampliando automáticamente el array más pequeño a lo largo de un eje compatible hasta que tenga la misma forma que el array más grande.

   - **Concepto Clave**:
     - Solo se puede realizar broadcasting si todas las dimensiones de los arrays son iguales o una de ellas es 1.

2. **Reglas del Broadcasting**

   Para aplicar el broadcasting, NumPy sigue un conjunto de reglas para determinar la interacción entre las dimensiones de los arrays:

   - **Regla 1**: Si los arrays no tienen el mismo número de dimensiones, se añade una dimensión de tamaño 1 al inicio del array con menos dimensiones.
   - **Regla 2**: Se comparan las dimensiones de los arrays. Si las dimensiones son iguales o una de ellas es 1, se puede continuar. Si no, se produce un error.
   - **Regla 3**: Los arrays con dimensiones de tamaño 1 se expanden para coincidir con las otras dimensiones.

   - **Ejemplo Visual**:
     - Considere un array `A` con dimensiones (5,1) y un array `B` con dimensiones (1,4). Según las reglas de broadcasting, ambos arrays se expandirían a (5,4) para realizar operaciones entre ellos.

In [2]:
import numpy as np

In [3]:
vector = np.array([1, 2, 3])

In [6]:
vector+5

array([6, 7, 8])

In [7]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[1], [2], [3]])

In [8]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
print(B)

[[1]
 [2]
 [3]]


In [10]:
A*B

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [21, 24, 27]])