In [1]:
import numpy as np

In [23]:
a = np.array([1, 5, 9])
b = np.array([4, 5, 6])

In [4]:
np.add(a,b)

array([5, 7, 9])

In [6]:
np.subtract(a,b)

array([-3, -3, -3])

In [7]:
np.multiply(a,b)

array([ 4, 10, 18])

In [8]:
np.divide(a,b)

array([0.25, 0.4 , 0.5 ])

In [14]:
angles = np.array([0, 30, 60, 90])
angles_rad = np.radians(angles)

In [17]:
np.tan(angles_rad)

array([0.00000000e+00, 5.77350269e-01, 1.73205081e+00, 1.63312394e+16])

In [24]:
np.equal(a,b)

array([False,  True, False])

In [26]:
np.power(a,b)

array([     1,   3125, 531441])

In [30]:
np.std(b)

0.816496580927726

In [33]:
print(a)
print(b)

[1 5 9]
[4 5 6]


In [37]:
z = a+b

In [41]:
w = np.add(a,b, dtype = np.int32)

In [42]:
type(w[0])

numpy.int32