In [1]:
import numpy as np

In [2]:
z = np.array([2,3,4])
x = z.copy()

z[1] = 9

In [3]:
print('x: ',x)
print('z: ',z)

x:  [2 3 4]
z:  [2 9 4]


In [4]:
a = np.arange(1, 10)
print(a)
b = a.reshape((3, 3))
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
c = b.flatten()
print(c)

[1 2 3 4 5 6 7 8 9]


In [6]:
d = b.ravel()
print(d)

[1 2 3 4 5 6 7 8 9]


In [7]:
d[0] = 99

In [8]:
b

array([[99,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [9]:
print(b)

[[99  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [10]:
b.transpose()

array([[99,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9]])

In [11]:
np.std(b)

29.46351583623548

In [12]:
np.min(b, axis = 1)

array([2, 4, 7])