In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

In [6]:
C = np.dot(A,B)
print(C)

[[ 4  4]
 [10  8]]


In [7]:
D = A @ B
print(D)

[[ 4  4]
 [10  8]]


In [8]:
x = np.array([2,3])
y = np.array([5,2])

In [9]:
x @ y

16

In [11]:
np.linalg.det(B)

4.0

In [12]:
print(B)

[[2 0]
 [1 2]]


In [15]:
det_A = np.linalg.det(A)
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inversa de A:\n", inv_A)
else:
    print("A no es invertible.")


Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [16]:
M = np.array([[3,3],[3,3]])

In [18]:
det_M = np.linalg.det(M)
print(det_M)
if det_M != 0:
    inv_M = np.linalg.inv(M)
    print("Inversa de M:\n", inv_M)
else:
    print("M no es invertible.")

0.0
M no es invertible.


In [19]:
print(A)

[[1 2]
 [3 4]]


In [20]:
Q, R = np.linalg.qr(A)

In [21]:
print("Factor Q:\n", Q)
print("Factor R:\n", R)

Factor Q:
 [[-0.31622777 -0.9486833 ]
 [-0.9486833   0.31622777]]
Factor R:
 [[-3.16227766 -4.42718872]
 [ 0.         -0.63245553]]


In [22]:
Q @ R

array([[1., 2.],
       [3., 4.]])