In [7]:
import numpy as np

### Sistema Resuelto con `np.linalg.solve`

$$
\begin{aligned}
3x + y &= 9\\
x + 2y &= 8
\end{aligned}
$$

El sistema en forma matricial \( Ax = b \) sería:

$$
A = \begin{bmatrix}
3 & 1 \\
1 & 2 
\end{bmatrix}, \quad
b = \begin{bmatrix}
9 \\
8 
\end{bmatrix}
$$

La solución, $ x $, que satisface $Ax = b $ se calcula mediante `np.linalg.solve`.


In [11]:
A = np.array([[3, 1], [1, 2]])
print(A)
b = np.array([9, 8])
print(b)
x = np.linalg.solve(A, b)
print("Solución del sistema:", x)


[[3 1]
 [1 2]]
[9 8]
Solución del sistema: [2. 3.]


In [12]:
print("Verificación de Ax = b:", np.dot(A, x))



Verificación de Ax = b: [9. 8.]


### Sistema Resuelto con la Pseudoinversa (`np.linalg.pinv`)

Sistema sobredeterminado (más ecuaciones que incógnitas):

$$
\begin{aligned}
x + 2y &= 1 \\
3x + 4y &= 2 \\
5x + 6y &= 3 
\end{aligned}
$$

El sistema en forma matricial $ Ax = b $ sería:

$$
A = \begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}, \quad
b = \begin{bmatrix}
1 \\
2 \\
3
\end{bmatrix}
$$

Utilizando la pseudoinversa de $ A $ y el método de mínimos cuadrados, encontramos una solución $ x $ que minimiza $ \| Ax - b \| $.

In [14]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)
b = np.array([1, 2, 3])
print(b)

[[1 2]
 [3 4]
 [5 6]]
[1 2 3]


In [15]:
A_pinv = np.linalg.pinv(A)
print(A_pinv)

[[-1.33333333 -0.33333333  0.66666667]
 [ 1.08333333  0.33333333 -0.41666667]]


In [16]:
x = np.dot(A_pinv, b)
print(x)

[0.  0.5]
