In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5])
for i in range(len(a)):
    a[i] += 2
print(a)

[3 4 5 6 7]


In [3]:
a = np.array([1, 2, 3, 4, 5])
a += 2
print(a)

[3 4 5 6 7]


In [4]:
b = np.array([2, 3, 5, 7, 11])

In [5]:
np.sin(a)+np.log(b)

array([0.83426719, 0.34180979, 0.65051364, 1.66649465, 3.05488187])

In [6]:
c = np.array([1, 2, 3, 4, 5])
d = c[:3]
d[0] = 100
print(c)

[100   2   3   4   5]


In [7]:
e = c[:3].copy()
e[0] = 10
print(c)

[100   2   3   4   5]


In [8]:
f = np.array([1, 2, 3], dtype=np.int32)

In [9]:
g = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(g)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
h = g[g > 5] 
print(h)

[6 7 8 9]


In [11]:
i = np.array([1, 2, 3])
print(i)
j = np.array([1, 2, 3]).reshape((3, 1))
print(j)

[1 2 3]
[[1]
 [2]
 [3]]


In [12]:
def is_even(num):
    return num % 2 == 0

In [13]:
vectorized_is_even = np.vectorize(is_even)


In [14]:
numbers = np.array([1, 2, 3, 4, 5, 6])

In [15]:
results = vectorized_is_even(numbers)
print(results) 

[False  True False  True False  True]
