Funciones universales en NumPy.
Objetivo: Escribe un programa que demuestre el uso de funciones universales (ufunc) en NumPy para realizar operaciones matemáticas en un array. Este ejercicio te ayudará a comprender cómo aplicar funciones universales para manipular datos de manera eficiente. El programa debe:

Crear un array de NumPy con valores enteros.

Aplicar varias funciones universales a este array, incluyendo operaciones de redondeo, potencias y comparaciones.

Mostrar los resultados de las operaciones.

Explicación detallada

Crear un array de NumPy:

Se crea un array de NumPy arr con valores decimales y negativos [-2.5, 1.7, 3.8, -1.2, 4.9].

Aplicar funciones universales (ufunc):

np.abs(arr): Calcula el valor absoluto de cada elemento del array, es decir, convierte los números negativos en positivos.

np.ceil(arr): Redondea cada elemento hacia el número entero más cercano por arriba (hacia el infinito).

np.floor(arr): Redondea cada elemento hacia el número entero más cercano por abajo (hacia menos infinito).

np.power(arr, 2): Eleva cada elemento del array al cuadrado.

np.sign(arr): Devuelve el signo de cada elemento del array: -1 para números negativos, 0 para cero, y 1 para números positivos.

Mostrar los resultados:

Se utilizan las funciones print para mostrar el array original y los resultados de las operaciones aplicadas.

In [ ]:
import numpy as np


ModuleNotFoundError: No module named 'scipy'

In [10]:
X = np.array([[-2.5, 1.7, 3.8, -1.2, 4.9]])
# Calcula el valor absoluto de cada elemento del array, es decir, convierte los números negativos en positivos.
valor_absoluto = np.abs(X)
print(f"Valor absoluto: {valor_absoluto}")

# Redondea cada elemento hacia el número entero más cercano por arriba (hacia el infinito).
redondeo_arriba = np.ceil(X)
print(f"Redondeo hacia arriba: {redondeo_arriba}")

# Redondea cada elemento hacia el número entero más cercano por abajo (hacia menos infinito).
redondeo_abajo = np.floor(X)
print(f"Redondeo hacia abajo: {redondeo_abajo}")

# Eleva cada elemento del array al cuadrado.
cuadrado = np.power(X, 2)
print(f"Cuadrado: {cuadrado}")

#Devuelve el signo de cada elemento del array: -1 para números negativos, 0 para cero, y 1 para números positivos.
signo = np.sign(X)
print(f"Signo: {signo}")

#Devuelve el valor máximo de cada elemento del array.
maximo = np.max(X)
print(f"Máximo: {maximo}")

#Devuelve el valor mínimo de cada elemento del array.
minimo = np.min(X)
print(f"Mínimo: {minimo}")

Valor absoluto: [[2.5 1.7 3.8 1.2 4.9]]
Redondeo hacia arriba: [[-2.  2.  4. -1.  5.]]
Redondeo hacia abajo: [[-3.  1.  3. -2.  4.]]
Cuadrado: [[ 6.25  2.89 14.44  1.44 24.01]]
Signo: [[-1.  1.  1. -1.  1.]]
Máximo: 4.9
Mínimo: -2.5


Manipulación avanzada de arrays en NumPy.
Objetivo: Escribe un programa que realice las siguientes operaciones utilizando arrays de NumPy:

Crear un array unidimensional con los números del 1 al 16.

Convertir el array unidimensional en una matriz 4x4.

Calcular la transpuesta de la matriz.

Obtener la diagonal principal de la matriz.

Calcular la suma de todos los elementos de la matriz.

Descripción de la solución: En Python, NumPy es una biblioteca poderosa para manipular arrays y matrices. Tu programa debe utilizar NumPy para crear y manipular arrays y matrices de acuerdo a las instrucciones especificadas.

In [11]:
# Crear un array unidimensional con los números del 1 al 16.
array_1 = np.arange(1,17)

# Convertir el array unidimensional en una matriz 4x4.
array_1 = array_1.reshape(4,4)

# Calcular la transpuesta de la matriz.
transpuesta = array_1.T

# Obtener la diagonal principal de la matriz.
diagonal = np.diag(array_1)

# Calcular la suma de todos los elementos de la matriz.
suma = np.sum(array_1)  

print(f"Matriz original: \n {array_1}")
print(f"Transpuesta: \n {transpuesta}")
print(f"Diagonal: \n {diagonal}")
print(f"Suma: \n {suma}")

Matriz original: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpuesta: 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Diagonal: 
 [ 1  6 11 16]
Suma: 
 136


Uso avanzado de broadcasting en NumPy.
Objetivo: Escribe un programa que utilice broadcasting en NumPy para realizar las siguientes operaciones:

Crear un array unidimensional con los números del 1 al 10.

Crear una matriz 3x3 con todos sus elementos iguales a 2.

Utilizar broadcasting para multiplicar cada elemento del array por cada elemento de la matriz.

Sumar cada columna de la matriz resultante.

Calcular el promedio de cada fila de la matriz resultante.

Descripción de la solución: En Python, NumPy permite realizar operaciones matemáticas eficientes mediante el uso de broadcasting. Tu programa debe crear arrays y matrices y aplicar operaciones utilizando broadcasting para multiplicar y sumar elementos de forma eficiente.

In [12]:
# Crear un array unidimensional con los números del 1 al 10.
array_1 = np.arange(1,11)

# Crear una matriz 3x3 con todos sus elementos iguales a 2.
array_2 = np.full((3,3),2)

# Para broadcasting, ajustamos la forma de 'a' para que coincida en la multiplicación
a_broadcast = array_1[:3].reshape(3,1) 

#Utilizar broadcasting para multiplicar cada elemento del array por cada elemento de la matriz
array_3 = a_broadcast * array_2

# Sumar cada columna de la matriz resultante.
suma_columnas = np.sum(array_3,axis=0)


# Calcular el promedio de cada fila de la matriz resultante.
promedio_filas = np.mean(array_3,axis=1)

print(f"Array 1: \n {array_1}")
print(f"Array 2: \n {array_2}")
print(f"Array 3: \n {array_3}")
print(f"Suma de columnas: \n {suma_columnas}")
print(f"Promedio de filas: \n {promedio_filas}")

Array 1: 
 [ 1  2  3  4  5  6  7  8  9 10]
Array 2: 
 [[2 2 2]
 [2 2 2]
 [2 2 2]]
Array 3: 
 [[2 2 2]
 [4 4 4]
 [6 6 6]]
Suma de columnas: 
 [12 12 12]
Promedio de filas: 
 [2. 4. 6.]



Operaciones avanzadas de álgebra lineal con NumPy.
Objetivo: Escribe un programa que realice las siguientes operaciones de álgebra lineal utilizando NumPy:

Crear dos matrices aleatorias de tamaño 3x3.

Calcular el producto punto (dot product) de las dos matrices.

Calcular la matriz inversa de la primera matriz.

Calcular el determinante de la segunda matriz.

Resolver un sistema de ecuaciones lineales representado por la ecuación Ax=bAx=b, donde AA es la primera matriz y bb es un vector aleatorio de tamaño 3.

Descripción de la solución: En Python, NumPy ofrece funciones poderosas para realizar operaciones de álgebra lineal. Tu programa debe crear matrices aleatorias y realizar varias operaciones de álgebra lineal, como calcular productos punto, matrices inversas, determinantes y resolver sistemas de ecuaciones.



In [13]:
# Crear dos matrices aleatorias de tamaño 3x3.
np.random.seed(0)
matriz_1 = np.random.rand(3,3)
matriz_2 = np.random.rand(3,3)

# Calcular el producto punto (dot product) de las dos matrices.
producto_punto = np.dot(matriz_1,matriz_2)

# Calcular la matriz inversa de la primera matriz.
matriz_inversa = np.linalg.inv(matriz_1)

# Calcular el determinante de la segunda matriz.
matriz_2_determinante = np.linalg.det(matriz_2)

#Resolver un sistema de ecuaciones lineales representado por la ecuación Ax=bAx=b, donde AA es la primera matriz y bb es un vector aleatorio de tamaño 3.
b = np.random.rand(3)
ecuacion_lineal = np.linalg.solve(matriz_1,b)

print(f"Producto punto: \n {producto_punto}")
print(f"Matriz inversa: \n {matriz_inversa}")
print(f"Determinante de la segunda matriz: \n {matriz_2_determinante}")
print(f"Ecuación lineal: \n {ecuacion_lineal}") 
print(f"Matriz 1: \n {matriz_1}")
print(f"Matriz 2: \n {matriz_2}")
print(f"b: \n {b}")


Producto punto: 
 [[0.66921566 1.10867318 0.84294166]
 [0.50586194 0.83659006 0.85606497]
 [0.75831917 1.19135456 1.09715043]]
Matriz inversa: 
 [[ 1.98960852  1.79913766 -2.4503547 ]
 [ 2.87590887 -3.14471165  0.30888212]
 [-3.56482088  2.09314855  1.86454351]]
Determinante de la segunda matriz: 
 -0.11118115485935706
Ecuación lineal: 
 [ 0.71553687 -0.19575172  0.87175171]
Matriz 1: 
 [[0.5488135  0.71518937 0.60276338]
 [0.54488318 0.4236548  0.64589411]
 [0.43758721 0.891773   0.96366276]]
Matriz 2: 
 [[0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985]]
b: 
 [0.77815675 0.87001215 0.97861834]


Operaciones con matrices con NumPy.
Objetivo: Escribe un programa que demuestre cómo realizar operaciones básicas de álgebra lineal con matrices utilizando NumPy. Este ejercicio te ayudará a comprender cómo crear y manipular matrices, realizar operaciones de suma, multiplicación y calcular la transpuesta e inversa de una matriz. El programa debe:

Crear dos matrices utilizando NumPy.

Realizar operaciones básicas como la suma de matrices, multiplicación de matrices, y calcular la transpuesta e inversa de una matriz.

Mostrar los resultados de las operaciones.

Explicación detallada

Crear dos matrices utilizando NumPy:

Se crean dos matrices matriz_a y matriz_b utilizando arrays de NumPy con valores definidos.

Suma de matrices:

La suma de matrices se realiza utilizando el operador +, sumando los elementos correspondientes de matriz_a y matriz_b.

Multiplicación de matrices (producto de matrices):

La multiplicación de matrices se realiza utilizando la función np.dot, que calcula el producto matricial de matriz_a y matriz_b.

Transpuesta de una matriz:

La transposición de una matriz se realiza utilizando np.transpose, que intercambia las filas por columnas en matriz_a.

Inversa de una matriz:

La inversa de una matriz se calcula utilizando np.linalg.inv. Para asegurar que la matriz sea invertible, se utiliza una matriz matriz_b_invertible que es cuadrada y no singular.

Mostrar los resultados:

Se utilizan las funciones print para mostrar las matrices originales y los resultados de las operaciones.

In [20]:

matriz_a = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz_b = np.array([[10,11,12],[13,14,15],[16,17,18]])

#Suma de matrices
matriz_suma = matriz_a + matriz_b

#Multiplicacion de matrices
multiplicacion = np.dot(matriz_a,matriz_b)

#Transpuesta de una matriz
transpuesta_a = np.transpose(matriz_a)
transpuesta_b = np.transpose(matriz_b)



#Determinante de una matriz
determinante_a = np.linalg.det(matriz_a)
determinante_b = np.linalg.det(matriz_b)

print(f"Matriz a: \n {matriz_a}")
print(f"Matriz b: \n {matriz_b}")
print(f"Suma de matrices: \n {matriz_suma}")
print(f"Multiplicacion de matrices: \n {multiplicacion}")
print(f"Transpuesta de una matriz: \n {transpuesta_a}")
print(f"Transpuesta de una matriz: \n {transpuesta_b}")

print(f"Determinante de una matriz: \n {determinante_a}")
print(f"Determinante de una matriz: \n {determinante_b}")

Matriz a: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz b: 
 [[10 11 12]
 [13 14 15]
 [16 17 18]]
Suma de matrices: 
 [[11 13 15]
 [17 19 21]
 [23 25 27]]
Multiplicacion de matrices: 
 [[ 84  90  96]
 [201 216 231]
 [318 342 366]]
Transpuesta de una matriz: 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]
Transpuesta de una matriz: 
 [[10 13 16]
 [11 14 17]
 [12 15 18]]
Determinante de una matriz: 
 0.0
Determinante de una matriz: 
 0.0


Autovalores y autovectores con NumPy.
Objetivo: Escribe un programa que demuestre cómo calcular los autovalores y autovectores de una matriz cuadrada utilizando NumPy. Este ejercicio te ayudará a comprender cómo utilizar NumPy para realizar operaciones de álgebra lineal avanzadas. El programa debe:

Crear una matriz cuadrada utilizando NumPy.

Calcular los autovalores y autovectores de la matriz.

Mostrar los autovalores y autovectores resultantes.

Explicación detallada

Crear una matriz cuadrada utilizando NumPy:

Se define una matriz cuadrada matriz de 2x2 utilizando un array de NumPy. En este caso, la matriz es [[4, -2], [1, 1]].

Calcular los autovalores y autovectores de la matriz:

Se utiliza la función np.linalg.eig para calcular los autovalores y autovectores de la matriz.

np.linalg.eig devuelve dos arrays: uno para los autovalores y otro para los autovectores.

Mostrar los resultados:

Se utiliza la función print para mostrar la matriz original, los autovalores y los autovectores calculados.

In [21]:
matriz_cuadrada = np.array([[4, -2], [1, 1]])

autovalores, autovectores = np.linalg.eig(matriz_cuadrada)

print(f"Autovalores: \n {autovalores}")
print(f"Autovectores: \n {autovectores}")

Autovalores: 
 [3. 2.]
Autovectores: 
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


Reconstrucción de una matríz.
Objetivo: Escribe un programa que demuestre cómo reconstruir una matriz original a partir de su descomposición en valores singulares (SVD). Este ejercicio te ayudará a comprender cómo se puede descomponer una matriz en componentes fundamentales y luego volver a ensamblar estos componentes para obtener la matriz original. El programa debe:

Crear una matriz utilizando NumPy.

Calcular la descomposición en valores singulares (SVD) de la matriz.

Reconstruir la matriz original utilizando las matrices resultantes de la SVD.

Comparar la matriz reconstruida con la original para verificar la exactitud de la reconstrucción.

Explicación detallada

Crear una matriz utilizando NumPy:

Se define una matriz matriz_original de 3x2 utilizando un array de NumPy.

Calcular la descomposición en valores singulares (SVD):

Se utiliza la función np.linalg.svd para descomponer la matriz matriz_original en tres matrices: U, S, y Vt.

Reconstruir la matriz original a partir de su descomposición en valores singulares:

El vector S que contiene los valores singulares se convierte en una matriz diagonal S_matriz.

La matriz original se reconstruye multiplicando U, S_matriz, y Vt en el orden correcto utilizando np.dot.

Comparar la matriz reconstruida con la original:

Se compara la matriz reconstruida con la original utilizando la función np.allclose, que verifica si dos matrices son aproximadamente iguales considerando pequeñas diferencias numéricas debido a la precisión computacional.

Si las matrices son iguales, se imprime un mensaje indicando que la reconstrucción fue exitosa; de lo contrario, se indica que no coinciden.

In [23]:
matriz_original = np.array([[4, 0], [3, -5], [7, 2]])

#Calcular la descomposición en valores singulares (SVD) de la matriz.
U, S, Vt = np.linalg.svd(matriz_original)
#Reconstruir la matriz original utilizando las matrices resultantes de la SVD.
S_matriz = np.zeros((U.shape[0], Vt.shape[0]))
np.fill_diagonal(S_matriz, S)
# Reconstruir la matriz original
matriz_reconstruida = np.dot(U, np.dot(S_matriz, Vt))

# 4. Comparar la matriz reconstruida con la original
print("Matriz Original:\n", matriz_original)
print("Matriz Reconstruida:\n", matriz_reconstruida)

Matriz Original:
 [[ 4  0]
 [ 3 -5]
 [ 7  2]]
Matriz Reconstruida:
 [[ 4.00000000e+00  2.23737683e-16]
 [ 3.00000000e+00 -5.00000000e+00]
 [ 7.00000000e+00  2.00000000e+00]]


Solución de ecuaciones lineales con NumPy.
Objetivo: Escribe un programa que resuelva un sistema de ecuaciones lineales con múltiples variables y ecuaciones utilizando NumPy. Este ejercicio te ayudará a comprender cómo utilizar las funciones avanzadas de NumPy para resolver sistemas complejos de ecuaciones, incluyendo el manejo de matrices y vectores. El programa debe:

Definir un sistema de ecuaciones lineales representado por una matriz de coeficientes y un vector de términos independientes.

Resolver el sistema utilizando NumPy.

Verificar la solución calculada.

Mostrar los resultados.

Explicación detallada

Definir un sistema de ecuaciones lineales:

Se define una matriz A que contiene los coeficientes de las variables en el sistema de ecuaciones.

El vector b contiene los términos independientes (en el lado derecho de las ecuaciones).

Resolver el sistema utilizando NumPy:

Se utiliza la función np.linalg.solve(A, b) para resolver el sistema Ax=bAx = bAx=b, donde A es la matriz de coeficientes y b es el vector de términos independientes. La función devuelve el vector solución x que contiene los valores de las variables.

Verificar la solución calculada:

Se utiliza np.allclose para verificar que la multiplicación de A por la solución x sea aproximadamente igual al vector b, lo que confirmaría que la solución es correcta.

Mostrar los resultados:

Se muestran la matriz de coeficientes, el vector de términos independientes, y la solución encontrada para las variables x, y, y z.

También se informa si la solución es correcta o si hay algún error en los cálculos.

In [24]:
# 1. Definir un sistema de ecuaciones lineales utilizando una matriz de coeficientes y un vector de términos independientes
# Sistema de ejemplo:
# 3x + 2y - z = 1
# 2x - 2y + 4z = -2
# -x + 0.5y - z = 0

# Matriz de coeficientes (A)
A = np.array([
    [3, 2, -1],
    [2, -2, 4],
    [-1, 0.5, -1]
])

# Vector de términos independientes (b)
b = np.array([1, -2, 0])

# 2. Resolver el sistema utilizando NumPy
solucion = np.linalg.solve(A, b)

# 3. Verificar la solución calculada
verificacion = np.allclose(np.dot(A, solucion), b)

# 4. Mostrar los resultados
print("Matriz de coeficientes (A):\n", A)
print("\nVector de términos independientes (b):\n", b)
print("\nSolución del sistema (valores de x, y, z):\n", solucion)

if verificacion:
    print("\nLa solución es correcta. El producto A*x es igual a b.")
else:
    print("\nLa solución no es correcta. Verifica los cálculos.")


Matriz de coeficientes (A):
 [[ 3.   2.  -1. ]
 [ 2.  -2.   4. ]
 [-1.   0.5 -1. ]]

Vector de términos independientes (b):
 [ 1 -2  0]

Solución del sistema (valores de x, y, z):
 [ 1. -2. -2.]

La solución es correcta. El producto A*x es igual a b.


Método Gauss-Jordan con NumPy.
Objetivo: Escribe un programa que implemente el método de Gauss-Jordan para resolver un sistema de ecuaciones lineales. Este método es una técnica de eliminación que se utiliza para llevar una matriz a su forma escalonada reducida, lo que permite resolver sistemas de ecuaciones lineales de manera eficiente. El programa debe:

Definir una matriz aumentada que represente un sistema de ecuaciones lineales.

Implementar el método de Gauss-Jordan para reducir la matriz a su forma escalonada reducida.

Extraer las soluciones del sistema a partir de la matriz reducida.

Mostrar los resultados, incluyendo la matriz reducida y las soluciones.

Explicación detallada

Definir la matriz aumentada:

La matriz aumentada combina la matriz de coeficientes del sistema de ecuaciones con el vector de términos independientes en una sola matriz.

Implementar el método de Gauss-Jordan:

El método de Gauss-Jordan consiste en llevar la matriz aumentada a su forma escalonada reducida utilizando operaciones elementales de fila. Esto incluye:

Convertir el elemento pivote (diagonal principal) en 1.

Hacer que todos los elementos en la columna del pivote sean 0, excepto el pivote.

El algoritmo se aplica iterativamente a todas las filas de la matriz.

Extraer las soluciones:

Una vez que la matriz ha sido reducida a su forma escalonada, las soluciones se encuentran en la última columna de la matriz reducida.

Mostrar los resultados:

Se muestran la matriz aumentada original, la matriz reducida después de aplicar Gauss-Jordan, y las soluciones del sistema.

In [28]:
def gauss_jordan(matriz_aumentada):
    filas, columnas = matriz_aumentada.shape
    
    for i in range(filas):
        # Hacer que el pivote sea 1 dividiendo toda la fila por el valor del pivote
        pivote = matriz_aumentada[i, i]
        matriz_aumentada[i] = matriz_aumentada[i] / pivote
        
        # Hacer que todos los elementos en la columna del pivote (excepto el pivote) sean 0
        for j in range(filas):
            if i != j:
                factor = matriz_aumentada[j, i]
                matriz_aumentada[j] = matriz_aumentada[j] - factor * matriz_aumentada[i]
    
    return matriz_aumentada

# 1. Definir la matriz aumentada (incluye la matriz de coeficientes y el vector de términos independientes)
# Ejemplo de un sistema de 3 ecuaciones con 3 incógnitas:
# 2x + y - z = 8
# -3x - y + 2z = -11
# -2x + y + 2z = -3

matriz_aumentada = np.array([
    [2, 1, -1, 8],
    [-3, -1, 2, -11],
    [-2, 1, 2, -3]
], dtype=float)

# 2. Aplicar el método de Gauss-Jordan
matriz_reducida = gauss_jordan(matriz_aumentada.copy())

# 3. Extraer las soluciones (las últimas columnas después de la reducción)
soluciones = matriz_reducida[:, -1]

# 4. Mostrar los resultados
print("Matriz Aumentada Original:\n", matriz_aumentada)
print("\nMatriz Reducida por Gauss-Jordan:\n", matriz_reducida)
print("\nSoluciones del sistema (valores de x, y, z):\n", soluciones)

Matriz Aumentada Original:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]

Matriz Reducida por Gauss-Jordan:
 [[ 1.  0.  0.  2.]
 [ 0.  1.  0.  3.]
 [-0. -0.  1. -1.]]

Soluciones del sistema (valores de x, y, z):
 [ 2.  3. -1.]
